services:
  - type: web
    name: hospital-backend
    env: python
    buildCommand: |
      pip install -r Backend/requirements.txt
      cd Backend
      prisma generate
    startCommand: uvicorn Backend.app.main:app --host 0.0.0.0 --port $PORT
